name: Post LLM Review Comments

on:
  workflow_run:
    workflows: ["LLM-Powered Code Review + SonarQube"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  post-comments:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: llm-comments
          path: .

      - name: Post PR Review Comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const comments = JSON.parse(fs.readFileSync('llm_comments.json', 'utf8'));
            const pr = context.payload.workflow_run.pull_requests[0];

            for (const c of comments) {
              await github.rest.pulls.createReviewComment({
                owner: pr.base.repo.owner.login,
                repo: pr.base.repo.name,
                pull_number: pr.number,
                body: c.comment,
                path: c.file_path,
                line: c.line,
                side: 'RIGHT'
              });
            }
